apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000